name: Docker React CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Construir imagen Docker
        run: docker build -t docker-react-test -f Dockerfile.dev .

      - name: Ejecutar tests
        run: docker run -e CI=true docker-react-test npm test -- --watchAll=false
